"""MCP server: tool and resource definitions over `GenomicsService`.

This file only maps MCP parameters to request models. Adapters register handlers
through `genomics_mcp.registry`; they do not edit this file.
"""

from __future__ import annotations

import json
from typing import Annotated, Any, Literal

from mcp.server.mcpserver import MCPServer
from mcp.server.mcpserver.exceptions import ResourceError
from mcp_types import CallToolResult, TextContent, ToolAnnotations
from pydantic import BaseModel, Field

from genomics_mcp import __version__
from genomics_mcp.errors import redact
from genomics_mcp.models import (
    Dataset,
    EvidenceRecord,
    FileFormat,
    FileRef,
    Interval,
    LocalArtifact,
    Provenance,
    Reference,
    Sample,
    Study,
    TransferJob,
    VariantSpec,
)
from genomics_mcp.registry import OPERATIONS, Operation
from genomics_mcp.result import ToolResult
from genomics_mcp.service import GenomicsService

INSTRUCTIONS = """\
Genomic data retrieval and reference evidence. Intervals are 0-based half-open with an
explicit assembly; nothing is lifted over. VariantSpec.pos is VCF POS (1-based).
Results are envelopes with status ok/partial/error, provenance and explicit truncation.
Read genomics://capabilities to see which operations this build implements."""

Result = Annotated[CallToolResult, ToolResult]
MaxRecords = Annotated[int | None, Field(ge=1, description="Lower the record limit.")]
Sources = Annotated[list[str] | None, Field(description="Source names; default all available.")]

READ = ToolAnnotations(read_only_hint=True, open_world_hint=True)
LOCAL_WRITE = ToolAnnotations(read_only_hint=False, destructive_hint=False, open_world_hint=True)

SCHEMA_MODELS: dict[str, type[BaseModel]] = {
    "tool_result": ToolResult,
    "interval": Interval,
    "variant_spec": VariantSpec,
    "file_ref": FileRef,
    "provenance": Provenance,
    "study": Study,
    "dataset": Dataset,
    "sample": Sample,
    "reference": Reference,
    "evidence_record": EvidenceRecord,
    "transfer_job": TransferJob,
    "local_artifact": LocalArtifact,
}

_TOOL_DOCS: dict[Operation, str] = {
    Operation.LIST_SOURCES: "List data and reference sources, their state and supported operations.",
    Operation.SEARCH_DATASETS: "Search one archive/catalog for studies or datasets by text query.",
    Operation.DESCRIBE_DATASET: "Describe a study/dataset by native accession, with linked entities.",
    Operation.LIST_FILES: "List files of a study/dataset with format, size, checksums, index and readiness.",
    Operation.LIST_SAMPLES: "List samples of a study/dataset as supplied by the source.",
    Operation.GET_SAMPLE_METADATA: (
        "Get one sample's metadata and phenotype values exactly as supplied by the source."
    ),
    Operation.FETCH_FILE: (
        "Start a bounded download of a file (and index) to the local work dir. Returns a transfer "
        "job; files above the default limit need budget_bytes."
    ),
    Operation.GET_TRANSFER_STATUS: "Get progress/result of a transfer started by fetch_file.",
    Operation.CANCEL_TRANSFER: "Cancel a running transfer.",
    Operation.GET_READS: (
        "Alignments overlapping an interval from indexed BAM/CRAM. Flag filters follow samtools "
        "-f/-F. CRAM needs a matching reference unless self-contained."
    ),
    Operation.GET_COVERAGE: (
        "Read depth over an interval from indexed BAM/CRAM (default excludes UNMAP, SECONDARY, "
        "QCFAIL, DUP, like samtools depth)."
    ),
    Operation.GET_PILEUP: "Per-position base counts over an interval from indexed BAM/CRAM.",
    Operation.GET_VARIANTS: "Variant records and optional genotypes overlapping an interval (VCF/BCF).",
    Operation.GET_SEQUENCE: "Reference sequence for an interval from an indexed FASTA.",
    Operation.GET_FEATURES: "Features overlapping an interval from indexed BED/GFF3/GTF or bigBed.",
    Operation.GET_SIGNAL: "Signal values or binned summaries over an interval from bigWig.",
    Operation.INSPECT_LOCUS: (
        "Combine data from several files at one locus, plus public evidence. Values derived from "
        "private files are only sent to external sources if allow_external_annotation is true."
    ),
    Operation.COMPARE_SAMPLES: "Compare genotypes/coverage at an interval across files or samples.",
    Operation.RESOLVE_IDENTIFIER: "Resolve a gene/transcript/protein/variant identifier; reports ambiguity.",
    Operation.NORMALIZE_VARIANT: (
        "Normalize a variant (VCF-style, HGVS or rsID) on an explicit assembly with a trace."
    ),
    Operation.LOOKUP_VARIANT: (
        "Source-attributed evidence for a variant (ClinVar, gnomAD, Ensembl, optional Atlas). "
        "No consensus or clinical verdict."
    ),
    Operation.LOOKUP_GENE: "Gene identifiers, transcripts and source-attributed annotations.",
    Operation.LOOKUP_PROTEIN: "Protein identity, function and features from UniProt and cross-references.",
}


SUMMARY_MAX_CHARS = 2000


def summarize(result: ToolResult) -> str:
    """Short text for the MCP text block. The full envelope is in structuredContent.

    `max_response_bytes` bounds the serialized envelope; this summary adds at most
    SUMMARY_MAX_CHARS, so the wire response stays near the budget instead of doubling it.
    """
    parts = [f"{result.operation}: {result.status.value}"]
    if result.error is not None:
        parts.append(f"error {result.error.code.value}: {result.error.message}")
        if result.error.hint:
            parts.append(f"hint: {result.error.hint}")
    data = result.data
    if isinstance(data, dict) and isinstance(data.get("records"), list):
        parts.append(f"records: {len(data['records'])}")
    elif isinstance(data, list):
        parts.append(f"records: {len(data)}")
    elif isinstance(data, dict) and isinstance(data.get("by_source"), dict):
        parts.append(f"sources with data: {', '.join(sorted(data['by_source']))}")
    if result.truncation is not None:
        t = result.truncation
        parts.append(f"truncated ({t.reason}, returned {t.returned}, limit {t.limit})")
    if result.errors:
        failed = ", ".join(f"{e.source or '?'}={e.code.value}" for e in result.errors)
        parts.append(f"partial errors: {failed}")
    if result.warnings:
        parts.append(f"warnings: {len(result.warnings)}")
    parts.append("full result in structuredContent")
    text = "; ".join(parts)
    return text if len(text) <= SUMMARY_MAX_CHARS else text[: SUMMARY_MAX_CHARS - 3] + "..."


def to_call_result(result: ToolResult) -> CallToolResult:
    payload = result.model_dump(mode="json")
    return CallToolResult(
        content=[TextContent(type="text", text=summarize(result))],
        structured_content=payload,
        is_error=result.status == "error",
    )


def _describe(service: GenomicsService, op: Operation) -> str:
    base = _TOOL_DOCS[op]
    if not service.registry.is_available(op):
        epics = ", ".join(OPERATIONS[op].planned_epics)
        return f"{base}\nNot implemented in this build: returns error code 'unsupported' ({epics})."
    keys = service.registry.keys(op)
    return f"{base}\nAvailable for: {', '.join(keys)}." if keys else base


def build_server(service: GenomicsService) -> MCPServer:
    """Build the MCP server. The caller owns `service` and must `await service.aclose()`."""
    mcp = MCPServer(
        "genomics-mcp",
        title="Genomics MCP",
        instructions=INSTRUCTIONS,
        version=__version__,
        website_url="https://github.com/rewire-bio/genomics-mcp",
        log_level=service.settings.logging.level,
    )

    async def run(op: Operation, **arguments: Any) -> CallToolResult:
        return to_call_result(await service.call(op, arguments))

    def tool(op: Operation, annotations: ToolAnnotations = READ):
        return mcp.tool(name=op.value, description=_describe(service, op), annotations=annotations)

    # ---------------------------------------------------------------- discovery
    @tool(Operation.LIST_SOURCES)
    async def list_sources(
        kind: Literal["archive", "catalog", "reference", "storage", "local"] | None = None,
    ) -> Result:
        return await run(Operation.LIST_SOURCES, kind=kind)

    @tool(Operation.SEARCH_DATASETS)
    async def search_datasets(
        source: str,
        query: str,
        assembly: str | None = None,
        organism: str | None = None,
        max_records: MaxRecords = None,
        cursor: str | None = None,
    ) -> Result:
        return await run(
            Operation.SEARCH_DATASETS,
            source=source,
            query=query,
            assembly=assembly,
            organism=organism,
            max_records=max_records,
            cursor=cursor,
        )

    @tool(Operation.DESCRIBE_DATASET)
    async def describe_dataset(source: str, accession: str) -> Result:
        return await run(Operation.DESCRIBE_DATASET, source=source, accession=accession)

    @tool(Operation.LIST_FILES)
    async def list_files(
        source: str,
        accession: str,
        formats: list[FileFormat] | None = None,
        max_records: MaxRecords = None,
        cursor: str | None = None,
    ) -> Result:
        return await run(
            Operation.LIST_FILES,
            source=source,
            accession=accession,
            formats=formats,
            max_records=max_records,
            cursor=cursor,
        )

    @tool(Operation.LIST_SAMPLES)
    async def list_samples(
        source: str, accession: str, max_records: MaxRecords = None, cursor: str | None = None
    ) -> Result:
        return await run(
            Operation.LIST_SAMPLES,
            source=source,
            accession=accession,
            max_records=max_records,
            cursor=cursor,
        )

    @tool(Operation.GET_SAMPLE_METADATA)
    async def get_sample_metadata(source: str, accession: str) -> Result:
        return await run(Operation.GET_SAMPLE_METADATA, source=source, accession=accession)

    # ---------------------------------------------------------------- transfers
    @tool(Operation.FETCH_FILE, LOCAL_WRITE)
    async def fetch_file(
        file: FileRef,
        include_index: bool = True,
        budget_bytes: Annotated[int | None, Field(ge=1)] = None,
        verify_checksum: bool = True,
    ) -> Result:
        return await run(
            Operation.FETCH_FILE,
            file=file,
            include_index=include_index,
            budget_bytes=budget_bytes,
            verify_checksum=verify_checksum,
        )

    @tool(Operation.GET_TRANSFER_STATUS)
    async def get_transfer_status(transfer_id: str) -> Result:
        return await run(Operation.GET_TRANSFER_STATUS, transfer_id=transfer_id)

    @tool(Operation.CANCEL_TRANSFER, LOCAL_WRITE)
    async def cancel_transfer(transfer_id: str) -> Result:
        return await run(Operation.CANCEL_TRANSFER, transfer_id=transfer_id)

    # ---------------------------------------------------------------- genomics
    @tool(Operation.GET_READS)
    async def get_reads(
        file: FileRef,
        interval: Interval,
        reference: FileRef | None = None,
        min_mapping_quality: Annotated[int, Field(ge=0, le=255)] = 0,
        require_flags: Annotated[int, Field(ge=0, le=0xFFF)] = 0,
        exclude_flags: Annotated[int, Field(ge=0, le=0xFFF)] = 0,
        include_sequence: bool = False,
        max_records: MaxRecords = None,
    ) -> Result:
        return await run(
            Operation.GET_READS,
            file=file,
            interval=interval,
            reference=reference,
            min_mapping_quality=min_mapping_quality,
            require_flags=require_flags,
            exclude_flags=exclude_flags,
            include_sequence=include_sequence,
            max_records=max_records,
        )

    @tool(Operation.GET_COVERAGE)
    async def get_coverage(
        file: FileRef,
        interval: Interval,
        reference: FileRef | None = None,
        min_mapping_quality: Annotated[int, Field(ge=0, le=255)] = 0,
        min_base_quality: Annotated[int, Field(ge=0, le=93)] = 0,
        exclude_flags: Annotated[int, Field(ge=0, le=0xFFF)] = 0x704,
        bin_size: Annotated[int | None, Field(ge=1)] = None,
        max_records: MaxRecords = None,
    ) -> Result:
        return await run(
            Operation.GET_COVERAGE,
            file=file,
            interval=interval,
            reference=reference,
            min_mapping_quality=min_mapping_quality,
            min_base_quality=min_base_quality,
            exclude_flags=exclude_flags,
            bin_size=bin_size,
            max_records=max_records,
        )

    @tool(Operation.GET_PILEUP)
    async def get_pileup(
        file: FileRef,
        interval: Interval,
        reference: FileRef | None = None,
        min_mapping_quality: Annotated[int, Field(ge=0, le=255)] = 0,
        min_base_quality: Annotated[int, Field(ge=0, le=93)] = 13,
        exclude_flags: Annotated[int, Field(ge=0, le=0xFFF)] = 0x704,
        max_depth: Annotated[int, Field(ge=1)] = 8000,
        max_records: MaxRecords = None,
    ) -> Result:
        return await run(
            Operation.GET_PILEUP,
            file=file,
            interval=interval,
            reference=reference,
            min_mapping_quality=min_mapping_quality,
            min_base_quality=min_base_quality,
            exclude_flags=exclude_flags,
            max_depth=max_depth,
            max_records=max_records,
        )

    @tool(Operation.GET_VARIANTS)
    async def get_variants(
        file: FileRef,
        interval: Interval,
        samples: list[str] | None = None,
        include_genotypes: bool = True,
        pass_only: bool = False,
        max_records: MaxRecords = None,
    ) -> Result:
        return await run(
            Operation.GET_VARIANTS,
            file=file,
            interval=interval,
            samples=samples,
            include_genotypes=include_genotypes,
            pass_only=pass_only,
            max_records=max_records,
        )

    @tool(Operation.GET_SEQUENCE)
    async def get_sequence(file: FileRef, interval: Interval) -> Result:
        return await run(Operation.GET_SEQUENCE, file=file, interval=interval)

    @tool(Operation.GET_FEATURES)
    async def get_features(
        file: FileRef,
        interval: Interval,
        feature_types: list[str] | None = None,
        max_records: MaxRecords = None,
    ) -> Result:
        return await run(
            Operation.GET_FEATURES,
            file=file,
            interval=interval,
            feature_types=feature_types,
            max_records=max_records,
        )

    @tool(Operation.GET_SIGNAL)
    async def get_signal(
        file: FileRef,
        interval: Interval,
        bins: Annotated[int | None, Field(ge=1)] = None,
        summary: Literal["mean", "min", "max", "coverage", "std", "sum"] = "mean",
        max_records: MaxRecords = None,
    ) -> Result:
        return await run(
            Operation.GET_SIGNAL,
            file=file,
            interval=interval,
            bins=bins,
            summary=summary,
            max_records=max_records,
        )

    # ---------------------------------------------------------------- composition
    @tool(Operation.INSPECT_LOCUS)
    async def inspect_locus(
        interval: Interval,
        files: list[FileRef] | None = None,
        reference: FileRef | None = None,
        reference_sources: Sources = None,
        allow_external_annotation: bool = False,
        max_records: MaxRecords = None,
    ) -> Result:
        return await run(
            Operation.INSPECT_LOCUS,
            interval=interval,
            files=files or [],
            reference=reference,
            reference_sources=reference_sources,
            allow_external_annotation=allow_external_annotation,
            max_records=max_records,
        )

    @tool(Operation.COMPARE_SAMPLES)
    async def compare_samples(
        interval: Interval,
        files: list[FileRef],
        samples: list[str] | None = None,
        reference: FileRef | None = None,
        max_records: MaxRecords = None,
    ) -> Result:
        return await run(
            Operation.COMPARE_SAMPLES,
            interval=interval,
            files=files,
            samples=samples,
            reference=reference,
            max_records=max_records,
        )

    # ---------------------------------------------------------------- reference
    @tool(Operation.RESOLVE_IDENTIFIER)
    async def resolve_identifier(
        identifier: str,
        target_types: list[str] | None = None,
        assembly: str | None = None,
        sources: Sources = None,
    ) -> Result:
        return await run(
            Operation.RESOLVE_IDENTIFIER,
            identifier=identifier,
            target_types=target_types,
            assembly=assembly,
            sources=sources,
        )

    @tool(Operation.NORMALIZE_VARIANT)
    async def normalize_variant(
        variant: VariantSpec | None = None,
        hgvs: str | None = None,
        rsid: str | None = None,
        assembly: str | None = None,
        reference: FileRef | None = None,
        sources: Sources = None,
    ) -> Result:
        return await run(
            Operation.NORMALIZE_VARIANT,
            variant=variant,
            hgvs=hgvs,
            rsid=rsid,
            assembly=assembly,
            reference=reference,
            sources=sources,
        )

    @tool(Operation.LOOKUP_VARIANT)
    async def lookup_variant(
        variant: VariantSpec | None = None,
        hgvs: str | None = None,
        rsid: str | None = None,
        assembly: str | None = None,
        sources: Sources = None,
        include: list[str] | None = None,
    ) -> Result:
        return await run(
            Operation.LOOKUP_VARIANT,
            variant=variant,
            hgvs=hgvs,
            rsid=rsid,
            assembly=assembly,
            sources=sources,
            include=include,
        )

    @tool(Operation.LOOKUP_GENE)
    async def lookup_gene(
        gene: str,
        assembly: str | None = None,
        sources: Sources = None,
        include: list[str] | None = None,
    ) -> Result:
        return await run(
            Operation.LOOKUP_GENE, gene=gene, assembly=assembly, sources=sources, include=include
        )

    @tool(Operation.LOOKUP_PROTEIN)
    async def lookup_protein(protein: str, sources: Sources = None) -> Result:
        return await run(Operation.LOOKUP_PROTEIN, protein=protein, sources=sources)

    # ---------------------------------------------------------------- resources
    def dump(data: Any) -> str:
        return redact(json.dumps(data, indent=2, default=str))

    @mcp.resource(
        "genomics://capabilities",
        name="capabilities",
        description="Operations implemented in this build, handler keys and planned epics.",
        mime_type="application/json",
    )
    def capabilities() -> str:
        return dump(service.capabilities())

    @mcp.resource(
        "genomics://status",
        name="status",
        description="Source states and non-secret configuration summary.",
        mime_type="application/json",
    )
    def status() -> str:
        return dump(service.status())

    @mcp.resource(
        "genomics://schemas",
        name="schemas",
        description="Names of available JSON schemas.",
        mime_type="application/json",
    )
    def schema_index() -> str:
        return dump({"schemas": sorted(SCHEMA_MODELS)})

    @mcp.resource(
        "genomics://schemas/{name}",
        name="schema",
        description="JSON schema for a named model, e.g. tool_result, file_ref, interval.",
        mime_type="application/json",
    )
    def schema(name: str) -> str:
        model = SCHEMA_MODELS.get(name)
        if model is None:
            raise ResourceError(f"unknown schema {name!r}; see genomics://schemas")
        return json.dumps(model.model_json_schema(), indent=2)

    return mcp
